config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :cars

  resources :manufacturers

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer, presence: true
  validates :color, presence: true
  validates :year, presence: true,
              numericality: { greater_than: 1920 }
  validates :mileage, presence: true, numericality: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_path, notice: "Car was successfully created."
    else
      render :new, notice: "Your car could not be saved."
    end
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage, :description)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end


  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      redirect_to manufacturers_path, notice: "Manufacturer was successfully created."
    else
      render :new, notice: "Your manufacturer could not be saved."
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end

end

app/views/cars/index.html.erb
<h3>All Cars</h3>

<ol>
<% @cars.each do |car| %>
  <li>
    <ul>
      <li>Manufacturer: <%= car.manufacturer.name %></li>
      <li>Color: <%= car.color %></li>
      <li>Year: <%= car.year %></li>
      <li>Mileage: <%= car.mileage %></li>
      <%= link_to "Car Details", car_path(car) %>
    </ul>
  </li>
  <br>
<% end %>
</ol>

app/views/cars/new.html.erb
<h3>Create New Car</h3>

<%= form_for @car do |f| %>

  <% if @car.errors.any? %>
    <p>
      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </p>
  <% end %>

  <p>
    <%= f.label :manufacturer %>
    <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name)%>
  </p>

  <p>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </p>

  <p>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.label :mileage %>
    <%= f.text_field :mileage %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <%= f.submit %>

<% end %>

app/views/cars/show.html.erb
  <h3>Car #<%= @car.id %></h3>

    <ul>
      <li><strong>Manufacturer:</strong> <%= @car.manufacturer.name %></li>
      <li><strong>Color:</strong> <%= @car.color %></li>
      <li><strong>Year:</strong> <%= @car.year %></li>
      <li><strong>Mileage:</strong> <%= @car.mileage %></li>
      <li><strong>Description:</strong> <%= @car.description %></li>
    </ul>

app/views/homes/index.html.erb
<p>
  <%= link_to 'All Cars', cars_path %> <br>
  <%= link_to 'New Cars', new_car_path %> <br>
  <%= link_to 'All Manufacturers', manufacturers_path %> <br>
  <%= link_to 'New Manufacturer', new_manufacturer_path %> <br>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">CarListings</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="left">
          <li><%= link_to 'All Cars', cars_path %></li>
          <li><%= link_to 'New Car', new_car_path %></li>
          <li><%= link_to 'All Manufacturers', manufacturers_path %></li>
          <li><%= link_to 'New Manufacturer', new_manufacturer_path %></li>
      </ul>
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>
<div class="row">
  <%= yield %>
</div>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/manufacturers/index.html.erb
<h3>All Manufacturers</h3>

<ol>
<% @manufacturers.each do |manufacturer| %>

  <li>
    Name: <%= manufacturer.name %> <br>
    Country: <%= manufacturer.country %><br>
  </li>
<br>
<% end %>
</ol>

app/views/manufacturers/new.html.erb
<h3>Create New Manufacturer</h3>

<%= form_for @manufacturer do |f| %>

 <% if @manufacturer.errors.any? %>
    <p>
      <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </p>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :country %>
    <%= f.text_field :country %>
  </p>

  <%= f.submit %>

<% end %>